version: 5.1.0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2022
configuration: Release
platform: Any CPU
force_https_clone: true
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST: https://www.nuget.org
  NUGET_APIKEY: 
    secure: wqyy7iEYocN/b3YAG+vtgMqCUiP9jUIYr0B4WNKa3pPvogJiLxr5DizMfsaKqc51
build: off
build_script:
- ps: >-
    dotnet build .\GoogleApi.sln;
test: off
test_script:
- ps: >-
    dotnet test .\.tests\GoogleApi.UnitTests\GoogleApi.UnitTests.csproj
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
- path: '**\*.snupkg'
  name: NuGet Symbol Package
deploy:
- provider: NuGet
  server: $(NUGET_HOST)
  api_key: $(NUGET_APIKEY)
  on:
    branch: master